### ISSUE TITLE
Please, make more specific part about contribution in Readme.md

### ISSUE THREAD

**Issue by shologin** [marwin1991/profile-technology-icons#170]
Hi! I have a desire to contribute to this amazing project, but I've been little buffled about the terms of contribution. There is no specification how to add the icon to the project. Should one give the internal source of the icon, or load to some folder? It's only stated about the size of the picture.
It would be great to make some ammends to the file Readme.md in part of contribution and give more wide explanation how to add the icon.
Thanks.

**Comment by marwin1991** [comment]
@shologin can you modify README.md and include more information about contribiution from your perspective ? :)

**Comment by shologin** [comment]
@marwin1991 ok, I'll manage it.
