### ISSUE TITLE
It would be great to add "Static sites generators" section to README.md

### ISSUE THREAD

**Issue by shologin** [marwin1991/profile-technology-icons#176]
It would be fantastic if user could find icons such as Next, Nuxt, Gatsby etc. in this project. I guess in might be a separate section for static site generators.
@marwin1991 can I nail it?

**Comment by marwin1991** [comment]
@shologin Cool idea! But `Gatsby is a React-based open source framework ` so I dont know if `section for static site generators` is a good idea, maybe put it to Java Script section ?

**Comment by shologin** [comment]
@marwin1991 okey dokey, I'll figure this out.
