### ISSUE TITLE
To which category should we put Openresty icon?

### ISSUE THREAD

**Issue by shologin** [marwin1991/profile-technology-icons#241]
@marwin1991, hi! I'm a bit confused where to place openresty icon? Maybe it's gonna be in the Web Dev? Or should we open new category called "Backend"? How do you think?

**Comment by marwin1991** [comment]
What about DevOps section? 

https://github.com/marwin1991/profile-technology-icons#-devops

**Comment by marwin1991** [comment]
cc @shologin

**Comment by shologin** [comment]
@marwin1991 what's cc ? 😄

**Comment by marwin1991** [comment]
I think it means "carbon copy" and i use it to notify and mark users here (to get notification)

**Comment by shologin** [comment]
gotcha)
