### ISSUE TITLE
Add icons

### ISSUE THREAD

**Issue by joaopaulomoreira** [marwin1991/profile-technology-icons#40]
Hello!

Could you add the icons?
![Chai](https://user-images.githubusercontent.com/68279555/200387382-944dbebe-5814-4b0e-b89b-86c1dda0bf97.png)
![cypress](https://user-images.githubusercontent.com/68279555/200387386-276c709f-380b-46cc-81fd-f292985927a8.png)
![Mocha](https://user-images.githubusercontent.com/68279555/200387390-0dc076c0-f39f-408d-a0cf-7c6d172768d0.png)
![RobotFramework](https://user-images.githubusercontent.com/68279555/200387392-a9ff28d9-3a53-4ec2-a938-cc079ec60ca2.png)

**Comment by marwin1991** [comment]
Closed by #41
