### ISSUE TITLE
Not working here

### ISSUE THREAD

**Issue by joaosilva-lp** [marwin1991/profile-technology-icons#49]
Hi, this repository is really nice, however it doesn't work here, I tryed several browsers and devices and when I write the input it doesn't suggest anything, even if I write something like "Python" and then click in generate. Thanks

**Comment by marwin1991** [comment]
@joaosilva-lp Thank you so much for reporting this problem and contribiution to this project ❤️ 

If you need any help or new icons feel free to contact me anytime and I will do my best to help you !

One more time thank you so much !

**Comment by marwin1991** [comment]
I am so happy that I could help you :) Thank you one more time!
