### ISSUE TITLE
Icons as table

### ISSUE THREAD

**Issue by marwin1991** [marwin1991/profile-technology-icons#5]
Allow option to create icons as table:

![image](https://user-images.githubusercontent.com/25181517/190895156-c6d4feed-0f5a-45e3-a3b1-7d72cb370fe6.png)

**Comment by FleetAdmiralJakob** [comment]
As this was merged: **https://github.com/marwin1991/profile-technology-icons/pull/139**
And we now have an table option, I think this is done
![image](https://github.com/marwin1991/profile-technology-icons/assets/77451351/e3d84745-3de1-4d1c-bfd5-28b1d55a7cdc)
